// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNvI8cmZ1R0kh5PoryBnlKALRyuH1XITA',
    appId: '1:724631241230:web:a80d1abc76cf42083a725f',
    messagingSenderId: '724631241230',
    projectId: 'thebookwasbetter-d4381',
    authDomain: 'thebookwasbetter-d4381.firebaseapp.com',
    storageBucket: 'thebookwasbetter-d4381.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQ35yhkrNIpzGziv2aHQ4ezUNoR6wE3Q',
    appId: '1:724631241230:android:a086965c4651cec63a725f',
    messagingSenderId: '724631241230',
    projectId: 'thebookwasbetter-d4381',
    storageBucket: 'thebookwasbetter-d4381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgzIBVJ4gYOHmwg27VYNagKXBPLU0x8I',
    appId: '1:724631241230:ios:ab9a81186727cedf3a725f',
    messagingSenderId: '724631241230',
    projectId: 'thebookwasbetter-d4381',
    storageBucket: 'thebookwasbetter-d4381.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUgzIBVJ4gYOHmwg27VYNagKXBPLU0x8I',
    appId: '1:724631241230:ios:ab9a81186727cedf3a725f',
    messagingSenderId: '724631241230',
    projectId: 'thebookwasbetter-d4381',
    storageBucket: 'thebookwasbetter-d4381.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNvI8cmZ1R0kh5PoryBnlKALRyuH1XITA',
    appId: '1:724631241230:web:aa42404151cb0c603a725f',
    messagingSenderId: '724631241230',
    projectId: 'thebookwasbetter-d4381',
    authDomain: 'thebookwasbetter-d4381.firebaseapp.com',
    storageBucket: 'thebookwasbetter-d4381.firebasestorage.app',
  );
}
